# -*- coding: utf-8 -*-
# MARKER_TIMELINE_REALTIME_PROGRESS_V1 -- Timeline: Realtime ความคืบหน้า (broadcast ตอนบันทึก + รับ Event/Poll 60 วิ แล้วดึงใหม่)
import sys, io
path = sys.argv[1]
src = io.open(path, encoding="utf-8").read()
if "MARKER_TIMELINE_REALTIME_PROGRESS_V1" in src:
    print("already patched"); sys.exit(0)
REPS = [('import { broadcastWs } from "../wsManager";', 'import { broadcastWs } from "../wsManager";\nimport { useRealtimeRefresh } from "../useRealtimeRefresh"; // MARKER_TIMELINE_REALTIME_PROGRESS_V1'), ('    const tm = setTimeout(async () => {\n      for (const b of bus) {\n        const js = JSON.stringify(pickProg(b));\n        if (savedRef.current[b.bu] === js) continue;', '    const tm = setTimeout(async () => {\n      const savedBus = [];\n      for (const b of bus) {\n        const js = JSON.stringify(pickProg(b));\n        if (savedRef.current[b.bu] === js) continue;'), ('        else { savedRef.current[b.bu] = js; setSaveMsg(""); }\n      }\n    }, 600);\n    return () => clearTimeout(tm);\n  }, [bus, loadedProg, userName]);', '        else { savedRef.current[b.bu] = js; setSaveMsg(""); savedBus.push(b.bu); }\n      }\n      if (savedBus.length) broadcastWs("timeline_progress_updated", { period_ym: PERIOD_YM, bus: savedBus, by: userName || "" }); // Realtime: แจ้งเครื่องอื่นให้ดึงข้อมูลใหม่\n    }, 600);\n    return () => clearTimeout(tm);\n  }, [bus, loadedProg, userName]);\n  // MARKER_TIMELINE_REALTIME_PROGRESS_V1 -- รับ Event แล้วดึง timeline_progress ใหม่ (+ Poll สำรองทุก 60 วิ) · BU ที่เรามีแก้ค้างยังไม่บันทึกจะไม่ถูกทับ\n  const busRef = React.useRef(bus);\n  busRef.current = bus;\n  const refreshProgress = React.useCallback(async () => {\n    if (!loadedProg) return;\n    const r = await db.from("timeline_progress").select("*").eq("period_ym", PERIOD_YM);\n    if (!r || r.error || !Array.isArray(r.data)) return;\n    const updates = {};\n    r.data.forEach((row) => {\n      if (row.id) rowIdRef.current[row.bu] = row.id;\n      const b = busRef.current.find((x) => x.bu === row.bu);\n      if (!b || !row.state || typeof row.state !== "object") return;\n      if (JSON.stringify(pickProg(b)) !== savedRef.current[b.bu]) return; // เรามีแก้ค้างอยู่ ไม่ทับ\n      const m = mergeProg(b, row.state);\n      const js = JSON.stringify(pickProg(m));\n      if (js === savedRef.current[b.bu]) return; // ไม่มีอะไรเปลี่ยน\n      savedRef.current[b.bu] = js;\n      updates[b.bu] = { ...m, inScope: b.inScope, why: b.why };\n    });\n    if (Object.keys(updates).length) setBus((prev) => prev.map((b) => updates[b.bu] || b));\n  }, [loadedProg]);\n  useRealtimeRefresh(["timeline_progress_updated"], refreshProgress, 60000);')]
for o, n in REPS:
    assert src.count(o) == 1, "anchor: " + o[:50]
    src = src.replace(o, n)
io.open(path, "w", encoding="utf-8", newline="").write(src)
print("patched OK")
